l_hip_pitch:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200
  
l_hip_roll:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

l_hip_yaw:
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102
  feedforward_1st_gain: 0

l_knee_pitch:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

l_ankle_pitch:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502 
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

l_ankle_roll:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

r_hip_pitch:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0  
  profile_acceleration: 0
  feedforward_1st_gain: 200

r_hip_roll:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

r_hip_yaw:
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102
  feedforward_1st_gain: 0

r_knee_pitch:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0 
  profile_acceleration: 0
  feedforward_1st_gain: 200

r_ankle_pitch:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

r_ankle_roll:
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
  velocity_p_gain: 4500
  velocity_i_gain: 1500 
  position_p_gain: 502 
  profile_velocity: 0
  profile_acceleration: 0
  feedforward_1st_gain: 200

head_pitch:
  position_p_gain: 850
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102

head_yaw:
  position_p_gain: 850
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102
  
waist_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551

waist_yaw:
  position_p_gain: 850
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102
  

l_shoulder_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551

l_shoulder_roll:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
l_elbow_pitch:
  position_p_gain: 850
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102
  
r_shoulder_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
r_shoulder_roll:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
  second_goal_pos_addr1: 564
  second_goal_pos_addr2: 565
  second_goal_pos_addr3: 566
  second_goal_pos_addr4: 567
  second_goal_current_addr1: 550
  second_goal_current_addr2: 551
r_elbow_pitch:
  position_p_gain: 850
  return_delay_time: 10
  second_goal_pos_addr1: 116
  second_goal_pos_addr2: 117
  second_goal_pos_addr3: 118
  second_goal_pos_addr4: 119
  second_goal_current_addr1: 102
  second_goal_current_addr2: 102
